language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest -v
  - python freeze.py
deploy:
  provider: s3
  secret_access_key:
    secure: Qf1+3oIfFe0GZBtfSf3t+QxjRAYsznhOOYx7O5v3s6CS6KxCl23JtEprqxm9UUFIRBV6JkPYeXCLcIeR5ruv9Fg5zUqt1w4dWsWjBXQtxCskwrrTPngouM7Ud815lR7GstmISMsJxX396NbAw7YzACtoS1NJCWYFwTYopB7g/6AcD4WDSBKaiyUwl/aOzoqUDsqkTO8iNcQJyPvf5mcPJw2hB+QXIhFb1mDoWbKFZgqcxxptOHWSgQhdQC6mgAultzBkY0pWzCIYDoZlFDnPdK8TwEL/up5uh1bcfiMHZlvYXRvwK+k7jCUWWYfHrOf2i/Qa8o2MmDqH7vJo9fSd4xNZsAeb64CSNXlifpR7GW2UC7C0yJUX4Idg1neVFifkdrHpfGY2g4FCmF9ag/wC3w5ZMCgvUVJKiPJhnHcfhREwUE7AS23d/57uoXutH2AGZ3LddktB2pAt07OdsChrl1id38QL3Ncnq511wYGNiPFCAi6wvML3xxC5NfdQgxEQ8KLQrsgERaNW+1YnI0e4mbf4PWgd4DDEfvaRv54os2QLKpizJSA5yb04ri6kGyya15RQax4HLTltIDG1vNsS6viWLD+lEPaARyK6kD6Q7UynJ7/6oSWFGSzNKaUfd3amsiv3DWdClXqu9i48mpqurv91ffOq378YcTjiGJs8hxI=
  access_key_id:
    secure: dwWnPZ37Hyadi4BLj6gaRrdo2HBibWRhXQ7W/y10c+Sm88Y/a4ijauJWotgzyhvApq+kiS0XehIA/MmEN6mrNJvBrha4OkNJYAdbiT5vvrU5jJYKfaDfXUzHF3wNra2wB/sOq67s+QuvveVh1xzzrQWl1syOLe1OWk3LhnO0zNSNiEQBhwC6atkvW8Clw7R6RCKjRjAQhf5puNWlJPNMf8ZGxhGJGzkrKGiCQoK3uicHpCzU0YED7z9x15xA9dPqsNWETstFAAOQzYKlaVok7rIexQgeTXDC03SiJZ46HVTr0tCz1C1zBKNuMBKKYSwRJtQ+/pB53iTzWjeC+yMhn3wtb7ZwUA0Zwmk7H81Yc/yuOmAauAYqOQgsKYesIEeqYxn4fTqtpScauUSw/sE6NJj0bVqti46EnwV+HQhRRkK8+iob2QF16yUExvrUwUfFkzzOZuo+3fkVW0u5R6m3QFyB2ej1Fm3+/k4plH0EPbxnq6SIwFq9qRqWZxBZvziAA/KLiGwswT3a71E4uoCQOFvQ+4Fl45s1Sdow4EgOzGc1RT5mdYDaBSuu5teNnvCA3B0b1iQeuxdNouklIbsdO8yR0wEis2muZkGubAEzO7imxHLCz87Yz82pgG9iOMPZRt8VJDsXeew1b5bX/hIdUQrcy10hqDg/nM7AsvSpdSM=
  bucket: hraew.autophagy.io
  skip_cleanup: true
  region: eu-central-1
  local_dir: hraew/build
notifications:
  email: false
